default_language_version:
  python: default

# Note on language version:
# `default_language_version` is set to "default" to allow the pre-commit hooks
# to use the interpreter from the currently active environment. This improves
# compatibility across systems:
# - Locally, it uses the developer's active Python (e.g. 3.13 in Conda)
# - In GitHub Actions, it uses the job Python (e.g. 3.11)
# - In pre-commit.ci, it avoids errors when the exact version is unavailable
# This trades off strict reproducibility for convenience and compatibility.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2500"]
      - id: end-of-file-fixer
        exclude: '\.org$'
      - id: trailing-whitespace
        exclude: '\.org$'
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
