* Designplan
A simple game for learning a bit of python and how to use git and github together. This document is for making some sort of starting outline of the project.
** Overview
A text based game where you create a character and fight monsters one by one until you win or until you die. 
** Code style
Apparently we are doing Class objects with first letter capital syntax.
Examples: Map, Die, Character
May I suggest function name syntax: all lower-case letters, "-" between tags
Example: this-function-foo
And for variables i suggest all lower-case letters, "_" between tags
Example: number_of_sides_foo

Vertical spacing: I suggest vertical spacing between blocks of code for better
readability and seeing patterns in the code for how it's implemented.

TK : I suggest using PEP 8  https://peps.python.org/pep-0008/ for naming conventions and black for code style https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html
I'm not sure how it differs exactly from your suggestions other than "_" instead of "-" om variable names. The main upside is that

-- Code should aim for minimal sideeffects --
-- Code should aim for containing sideeffects either in main function or in separate files


** Program structure / dirs&files

Keep `txtDungeon dir' 'clean' : create folders and moves files there, except some main.

*** Design in the form of questions:
How much is rng?
** Global functions
*** python id()
*** imports
**** math
**** random
** Classes
*** Actions
**** attack
**** use
**** stats
**** bags
**** move
***** e
***** w
***** n
***** s
*** Map
*** Die
*** Character
**** name
**** position
**** CharStatPoints
linked list [int points, str "stat_nametag"]
like [{15:dextarity}{18:strength}{66:int}] //dunno syntax, do-look-up
**** ItemBar
***** str
***** dex
***** int
**** Status
***** saturation
***** hydration
***** hp
*** Monster
*** Item
**** offhand
**** mainhand
