name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install ruff==0.3.4
      - name: Run ruff format check
        run: ruff format --check .
      - name: Run ruff lint check
        run: ruff check . --output-format=github